services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Supseven\YamlConfiguration\:
    resource: '../Classes/*'

  Supseven\YamlConfiguration\Command\ExportTableCommand:
    tags:
      - name: 'console.command'
        command: 'yaml:export'
        schedulable: false

  Supseven\YamlConfiguration\Command\ImportTableCommand:
    tags:
      - name: 'console.command'
        command: 'yaml:import'
        schedulable: false

  Supseven\YamlConfiguration\Backend\ButtonBar\YamlExportButton:
    tags:
      - name: event.listener
        identifier: 'yaml-configuration/backend/yamlexportbutton'
