# Settings.yml
# -*- coding: utf-8 -*- with BOM. Umlaut-check: ÄÖÜäöüß
---
conf.py:
  todo_include_todos: True
  copyright: 2016
  project: YAML-Configuration
  version: 2.0
  release: 2.0.0
  html_theme_options:
    github_repository: georgringer/news
    github_branch: master
  latex_documents:
  - - Index
    - YAML-Configuration.tex
    - YAML-Configuration
    - Michiel Roos
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
      - http://docs.typo3.org/typo3cms/TyposcriptReference/
      - null
    t3start:
      - http://docs.typo3.org/typo3cms/GettingStartedTutorial/
      - null
    t3editors:
      - http://docs.typo3.org/typo3cms/EditorsTutorial/
      - null
...
